apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80           # Port within the cluster
      targetPort: 80      # Port the container is listening on
      nodePort: 30007     # Expose the service on localhost:30007
  type: NodePort