apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
  labels:
    app: web-portfolio
spec:
  selector:
    app: web-portfolio
  type: LoadBalancer
  ports:
  - port: 30100 #service port
    targetPort: 3000 #container port