apiVersion: v1
kind: Service
metadata:
  name: web-portfolio-service
spec:
  selector:
    app: web-portfolio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008
  type: NodePort