name: CI-tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Check if requirements.txt exists
        id: check_requirements
        run: |
          if [ -f "requirements.txt" ]; then
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "exists=false" >> $GITHUB_ENV
          fi

      - name: Install dependencies (only if requirements.txt exists)
        if: env.exists == 'true'
        run: pip install -r requirements.txt

      - name: Run test script 1
        run: pytest test-scripts/demo-test1.py

      - name: Run test script 2
        run: pytest test-scripts/demo-test2.py


name: Build and Push NGINX Docker Image

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build_and_push_to_dockerhub:
    runs-on: ubuntu-latest
    needs: CI-tests

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./dockerfile
        push: true
        tags: thaworapong/testing:latest
